apiVersion: v1
kind: Secret
metadata:
  name: numaflow-dex-secrets
stringData:
  # https://dexidp.io/docs/connectors/github/
  dex-github-client-id: c8a5fdd9f0c0a4a0327e
  dex-github-client-secret: 20f8864d3b7f6852a6c3656a1b8b31bb221b5710