---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: e2epod-role
    namespace: numaflow-system
rules:
    - apiGroups:
        - ''
      resources:
        - 'pods'
      verbs:
        - 'create'
        - 'delete'
        - 'get'
        - 'list'
        - 'patch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: e2e-rolebind
subjects:
    - kind: ServiceAccount
      name: default
      namespace: numaflow-system
roleRef:
    kind: Role
    name: e2epod-role
    apiGroup: rbac.authorization.k8s.io
